### ISSUE TITLE
GeyserMC support issue with bedrock players rtping

### ISSUE THREAD

**Issue by Zekernn** [DailyStruggle/RTP#32] opened 2023-02-16 20:16 UTC
When bedrock players type /rtp, nothing happens nor does it say anything. I don't see any errors at all. I'm on the latest version of the plugin, as well as purpur mc 1.19.2.

Java players don't have an issue at all, only bedrock.

Does RTP support geysermc?

Here's it shows in the console:
[https://gyazo.com/0777d2717bf3b7b9169333d9fb48c5c2](url)

**Comment by DailyStruggle** [comment] 2023-02-16 20:55
I have never tested with geysermc/floodgate.

Your link seems a bit broken, it takes me to this issue tracker. Also, you should be able to paste some logs in code blocks here.

I'll give it a go this weekend, but I have no idea what geyser does for command processing.

Can you confirm that bedrock players can be teleported by console and/or operators?

`rtp player:[name]`

**Comment by DailyStruggle** [comment] 2023-02-17 02:11
seems fine to me, using latest geyser and floodgate, accessed via 127.0.0.1

![image](https://user-images.githubusercontent.com/28832622/219530970-681125e4-ecd2-43cd-892a-77ea4dffedd8.png)

![image](https://user-images.githubusercontent.com/28832622/219531034-5bc07f21-1ddf-42d7-9cea-a60290c4ff2a.png)

![image](https://user-images.githubusercontent.com/28832622/219531226-893f0d5e-ad95-4180-83a8-d90518ccf4e5.png)

I need more information about the setup to recreate this behavior.

**Comment by Zekernn** [comment] 2023-02-18 16:15
> seems fine to me, using latest geyser and floodgate, accessed via 127.0.0.1
> 
> ![image](https://user-images.githubusercontent.com/28832622/219530970-681125e4-ecd2-43cd-892a-77ea4dffedd8.png)
> 
> ![image](https://user-images.githubusercontent.com/28832622/219531034-5bc07f21-1ddf-42d7-9cea-a60290c4ff2a.png)
> 
> ![image](https://user-images.githubusercontent.com/28832622/219531226-893f0d5e-ad95-4180-83a8-d90518ccf4e5.png)
> 
> I need more information about the setup to recreate this behavior.

Strange. I'm not on my server atm, but when I do log on I'll make sure to provide you with logs, and other details as well.

**Comment by Zekernn** [comment] 2023-02-18 16:16
Should be on later today

**Comment by Zekernn** [comment] 2023-02-19 19:28
I've actually found an alternative for the time being, and It's temporarily resolved my issue. I appreciate the help, and if I need anything else I'll let you know.

**Comment by DailyStruggle** [comment] 2023-02-19 20:47
Heads up, this is an issue tracker, not a support channel. Its for everyone to see and chime in on a code issue, rather than "my issue".

Information related to the issue and the context it exists in (e.g. server build, plugin builds, and configuration) is necessary upfront so that devs and operators can reproduce or identify the same issue on another server.

**Comment by DailyStruggle** [comment] 2023-02-26 00:00
unable to reproduce this and missing instructions, closing for now

**Closed as completed by DailyStruggle** 2023-02-26 00:00 UTC
